### ISSUE TITLE
Incorrect Multiplication on Javascript Operators

### ISSUE THREAD

**Issue by dresean** [LambdaSchool/CS-Wiki#2]
It should be * instead of +

**Comment by fellanonymous** [comment]
To expand on this issue, I believe @dresean is referencing the following areas to your JAvascript Python cheatsheet.

https://github.com/LambdaSchool/CS-Wiki/wiki/Javascript-Python-cheatsheet#javascript-7

I also noticed this issue on the python table as well.

https://github.com/LambdaSchool/CS-Wiki/wiki/Javascript-Python-cheatsheet#python-7

**Comment by decagondev** [comment]
Fixed! 👍  Thanks for pointing it out 🔥
